# test this file with
#   goreleaser --skip-publish --rm-dist --config goreleaser.yml
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
archives:
  - 
    replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      amd64: x86_64
      386: x86
    format: gz
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: 'windows'
        format: 'zip'
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
